"""Timestamp in User Bonds

Revision ID: 032b004b95e4
Revises: e0e86f631bfa
Create Date: 2023-02-12 05:40:37.513168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032b004b95e4'
down_revision = 'e0e86f631bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('bond_price', sa.Float(), nullable=False),
    sa.Column('up_val', sa.Float(), nullable=True),
    
    sa.Column('down_val', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('face_value', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userbonds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('bond_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bond_id'], ['bonds.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userbonds_bond_id'), 'userbonds', ['bond_id'], unique=False)
    op.create_index(op.f('ix_userbonds_user_email'), 'userbonds', ['user_email'], unique=False)
    op.create_table('bondrequests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_email', sa.String(length=32), nullable=True),
    sa.Column('buyer_email', sa.String(length=32), nullable=True),
    sa.Column('user_bond_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('requested_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['user_bond_id'], ['userbonds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bondrequests_buyer_email'), 'bondrequests', ['buyer_email'], unique=False)
    op.create_index(op.f('ix_bondrequests_owner_email'), 'bondrequests', ['owner_email'], unique=False)
    op.create_index(op.f('ix_bondrequests_user_bond_id'), 'bondrequests', ['user_bond_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bondrequests_user_bond_id'), table_name='bondrequests')
    op.drop_index(op.f('ix_bondrequests_owner_email'), table_name='bondrequests')
    op.drop_index(op.f('ix_bondrequests_buyer_email'), table_name='bondrequests')
    op.drop_table('bondrequests')
    op.drop_index(op.f('ix_userbonds_user_email'), table_name='userbonds')
    op.drop_index(op.f('ix_userbonds_bond_id'), table_name='userbonds')
    op.drop_table('userbonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
