"""Added extra fields to users model

Revision ID: 0653b55945e6
Revises: 30ea62287170
Create Date: 2023-02-11 23:01:34.728171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0653b55945e6'
down_revision = '30ea62287170'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('aadhaar_no', sa.String(length=12), nullable=False))
    op.add_column('users', sa.Column('dob', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_users_aadhaar_no'), 'users', ['aadhaar_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_aadhaar_no'), table_name='users')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'aadhaar_no')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
