"""Company Name

Revision ID: 06fde45d1bee
Revises: 8b2b49b6a8e1
Create Date: 2023-02-12 07:41:14.501164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fde45d1bee'
down_revision = '8b2b49b6a8e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('company_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonds', 'company_name')
    # ### end Alembic commands ###
