"""Added Selling Status Field

Revision ID: 17ceb5b6c6f4
Revises: 38df103a5154
Create Date: 2023-02-12 09:24:08.923561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ceb5b6c6f4'
down_revision = '38df103a5154'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbonds', sa.Column('selling_status', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbonds', 'selling_status')
    # ### end Alembic commands ###
