"""Initial

Revision ID: 30ea62287170
Revises: 
Create Date: 2023-02-11 00:33:45.149313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30ea62287170'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('activation_code', sa.Float(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_table('resetpasswordrequest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=32), nullable=True),
    sa.Column('reset_code', sa.Float(), nullable=True),
    sa.Column('validity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resetpasswordrequest_reset_code'), 'resetpasswordrequest', ['reset_code'], unique=False)
    op.create_index(op.f('ix_resetpasswordrequest_user_email'), 'resetpasswordrequest', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resetpasswordrequest_user_email'), table_name='resetpasswordrequest')
    op.drop_index(op.f('ix_resetpasswordrequest_reset_code'), table_name='resetpasswordrequest')
    op.drop_table('resetpasswordrequest')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
