"""Account Balance

Revision ID: 3693d88cde3e
Revises: 0653b55945e6
Create Date: 2023-02-11 23:28:42.538275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3693d88cde3e'
down_revision = '0653b55945e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('account_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_balance')
    # ### end Alembic commands ###
