"""Device Token Added

Revision ID: 38df103a5154
Revises: 06fde45d1bee
Create Date: 2023-02-12 08:11:59.729303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38df103a5154'
down_revision = '06fde45d1bee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_token')
    # ### end Alembic commands ###
