"""Text field fix

Revision ID: 8b2b49b6a8e1
Revises: 8e7fdd52efe6
Create Date: 2023-02-12 06:31:48.774921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2b49b6a8e1'
down_revision = '8e7fdd52efe6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
