"""updated fields

Revision ID: 8e7fdd52efe6
Revises: 032b004b95e4
Create Date: 2023-02-12 06:08:04.277103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7fdd52efe6'
down_revision = '032b004b95e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
