"""New Models added

Revision ID: e0e86f631bfa
Revises: 3693d88cde3e
Create Date: 2023-02-12 04:24:43.431474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e86f631bfa'
down_revision = '3693d88cde3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
